name: flutterpro
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
  new_gradient_app_bar: ^0.2.0
  get:
  get_storage:
  dots_indicator:
  flutter_slidable: ^2.0.0
  introduction_screen:
  provider: 
  datetime_picker_formfield: ^2.0.1
  flutter_local_notifications:
  rxdart: 
  timezone: 
  #play Audio
  audioplayers: 

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  hive_generator: 
  build_runner: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/Audio/
    - assets/Audio/Done.wav
    - assets/Audio/Notification.mp3
    - assets/Audio/Add_Task.wav

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
